# Google Cloud Build configuration for CI/CD
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/solana-github-collector:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/solana-github-collector:latest'
      - '.'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/solana-github-collector:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/solana-github-collector:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'solana-github-collector'
      - '--image'
      - 'gcr.io/$PROJECT_ID/solana-github-collector:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '1'
      - '--set-env-vars'
      - 'NODE_ENV=production,ECOSYSTEM=solana'
      - '--set-secrets'
      - 'DB_HOST=DB_HOST:latest,DB_USERNAME=DB_USERNAME:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_NAME=DB_NAME:latest,GITHUB_TOKEN_1=GITHUB_TOKEN_1:latest,GITHUB_TOKEN_2=GITHUB_TOKEN_2:latest,GITHUB_TOKEN_3=GITHUB_TOKEN_3:latest,GITHUB_TOKEN_4=GITHUB_TOKEN_4:latest,GITHUB_TOKEN_5=GITHUB_TOKEN_5:latest'

images:
  - 'gcr.io/$PROJECT_ID/solana-github-collector:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/solana-github-collector:latest'

substitutions:
  _REGION: 'us-central1'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
